version: '3.6'
services:
  elasticsearch:
    build: ./elasticsearch
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - discovery.type=single-node
      - node.name=es01
      - xpack.security.enabled=false
      - xpack.license.self_generated.type=${LICENSE}
    ports:
      - 192.168.64.2:9200:9200
      - 192.168.64.2:9300:9300
    mem_limit: 2000000000

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.3
    links:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://192.168.64.2:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    ports:
      - 192.168.64.2:5601:5601
    mem_limit: 2000000000

