[tool.poetry]
name = "dezero"
version = "0.1.0"
description = ""
authors = ["tsukudamayo"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.23.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
